apiVersion: v1
kind: ConfigMap
metadata:
  name: django-configmap
data:
  PORT: "8080"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: content-pigeon-configmap
data:
  WELCOME_MSG: "WELCOME TO CONTENT PIGEON"
