apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-pigeon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: content-pigeon-pod
      labels:
        app: web
    spec:
      containers:
        - name: my-container
          image: rafa272011/content-engine-pigeon:latest
          env:
            - name: PORT
              value: "8080"
            - name: VERSION
              value: "1.0.1"
            - name: WELCOME_MSG
              valueFrom:
                configMapKeyRef:
                  name: content-pigeon-configmap
                  key: WELCOME_MSG
          #envFrom:
          #- configMapKeyRef:
          # name: django-configmap
          envFrom:
            - secretRef:
                name: content-pigeon-secret
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
