apiVersion: v1
kind: Service
metadata:
  name: content-pigeon
spec:
  selector:
    app: web
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80 #my domain.com --> mydomain.com:80
      targetPort: 8080
