apiVersion: v1
kind: Pod
metadata:
  name: content-pigeon-pod
  labels:
    app: contentpigeon
spec:
  containers:
    - name: my-container
      image: rafa272011/content-engine-pigeon:latest
      env:
        - name: PORT
          value: "8080"
        - name: WELCOME_MSG
          value: "welcom ESTAS AVANZANDO CONTINUA"
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
