name: Sync K8s Rollout

on:
  workflow_dispatch:

jobs:
  k8s_appply:
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_NAME: ${{secrets.DEPLOYMENT_NAME || 'content-pigeon'}}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
      - name: Configure Kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secret.KUBE_CONFIG }}" > ~/.kube/config
      - name: Apply K8s Manifest
        run: |
          kubectl apply -f k8s/
      - name: Trigger K8s Deployment Rollout
        run: |
          kubectl rollout restart deployments/${{ env.DEPLOYMENT_NAME}}
      - name: Verify K8s Deployment Rollout
        run: |
          kubectl rollout status deployments/${{ env.DEPLOYMENT_NAME}}
